version: '3.4'

services:
  registration.api:
    image: pikafoc/registrationapi
    build:
      context: .
      dockerfile: Services/Registration/Registration.API/Dockerfile


  emailservice.api:
    image: pikafoc/emailserviceapi
    build:
      context: .
      dockerfile: Services/Email/EmailService.API/Dockerfile


  signature.api:
    image: pikafoc/signatureapi
    build:
      context: .
      dockerfile: Services/Signature/Signature.API/Dockerfile


  smsservice.api:
    image: pikafoc/smsserviceapi
    build:
      context: .
      dockerfile: Services/SMS/SMSService.API/Dockerfile

  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2017-latest


  rabbitmq:
    image: rabbitmq:3-management-alpine


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2


  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2

volumes:
  elasticsearch-data:
