apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\admin\OneDrive\Desktop\STBEverywhere\Back-end\STB_Everywhere\kompose-windows-amd64.exe convert --file .\docker-compose.yml -f .\docker-compose.override.yml -v
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: emailservice-api
  name: emailservice.api
spec:
  ports:
    - name: "8005"
      port: 8005
      targetPort: 8080
  selector:
    io.kompose.service: emailservice-api
