lapiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: stbeverywhere
  name: stbeverywhere-api-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    http:
      paths:
      - path: /email
        pathType: Prefix
        backend:
          service:
            name: emailserviceapi
            port:
              number: 8080
      - path: /reg
        pathType: Prefix
        backend:
          service:
            name: registrationapi
            port:
              number: 8080
      - path: /sms
        pathType: Prefix
        backend:
          service:
            name: smsserviceapi
            port:
              number: 8080
      
