apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: signature-api-claim1
  name: signature-api-claim1
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
