apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stbeverywhere
  annotations:
    kompose.cmd: C:\Users\admin\OneDrive\Desktop\STBEverywhere\Back-end\STB_Everywhere\kompose-windows-amd64.exe convert --file .\docker-compose.yml -f .\docker-compose.override.yml -v
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: smsserviceapi
  name: smsserviceapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: smsserviceapi
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\admin\OneDrive\Desktop\STBEverywhere\Back-end\STB_Everywhere\kompose-windows-amd64.exe convert --file .\docker-compose.yml -f .\docker-compose.override.yml -v
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: smsserviceapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings_ConnectionString  # Changed from ConnectionStrings:ConnectionString
              value: "Server=sqlserverdb;Database=STBEverywhereDB;User Id=sa;Password=SwN12345678;TrustServerCertificate=true;"
            - name: ElasticConfiguration_Uri  # Changed from ElasticConfiguration:Uri
              value: "http://elasticsearch:9200"
          image: pikafoc/smsserviceapi:latest
          name: smsserviceapi
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
